version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: cmd/guandan-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - guandan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - guandan-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  guandan-network:
    driver: bridge

volumes:
  guandan-data:
    driver: local